baseURL = 'https://future.record.rat.la/'
languageCode = 'es-ES'
defaultContentLanguage = 'es'
title = 'record.rat.la'
# theme = 'hugo-theme-recordratla-sans-serif'
theme = 'hugo-theme-recordratla-bookstyle'
enableRobotsTXT = true
enableGitInfo = true
Paginate = 50
copyright = 'Esta obra está bajo una Licencia Creative Commons BY-SA-4.0. Y el código HTML y CSS bajo la GNU GPL v3.'
rssLimit = 15

[author]
  name = 'Inoro'

[Params]
  webRepo = 'https://github.com/1noro/record.rat.la-static'
  description = 'record.rat.la'
  github = 'https://github.com/1noro'
  gitlab = 'https://gitlab.com/1noro'
  mastodon = 'https://tilde.zone/@1noro'
  email = ''
  pgpPubKey = 'https://recordratla-public-res.s3.eu-south-2.amazonaws.com/publickey.ppuubblliicc%40protonmail.com.asc'
  articleDefaultImage = 'https://recordratla-public-res.s3.eu-south-2.amazonaws.com/img/common/article_default_img_peach.jpg'

[languages]
  [languages.es]
    languageName = 'Spanish'
    weight = 1

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 1

[taxonomies]
  tag = 'tags'
  # category = 'categories'
