baseURL = 'http://record.rat.la/'
languageCode = 'es-ES'
defaultContentLanguage = 'es'
title = 'record.rat.la'
theme = 'hugo-theme-recordratla-sans-serif'
enableRobotsTXT = true
enableGitInfo = true
Paginate = 5

[params]
  description = 'record.rat.la'
  author = 'Inoro'
  github = 'https://github.com/1noro'
  gitlab = 'https://gitlab.com/1noro'
  mastodon = 'https://tilde.zone/@1noro'
  # email = ''

[languages]
  [languages.es]
    languageName = 'Spanish'
    weight = 1
