description = "Book style theme for record.ra.la"
features = []
homepage = "https://rats.land/"
license = "GPL-3.0"
licenselink = "https://github.com/1noro/rats.land/blob/main/LICENSE"
min_version = "0.0.1"
name = "ratsland-bookstyle"
tags = ["blog", "clean", "minimal", "personal", "simple", "white"]

[author]
homepage = "https://github.com/1noro"
name = "Inoro"
